import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Poppins,
  Mona_Sans,
  Montserrat,
  Plus_Jakarta_Sans,
  Darumadrop_One,
  Tangerine,
  Italianno,
  Italiana,
  Figtree,
  Oswald,
} from "next/font/google";
import "./globals.css";

const italiana = Italiana({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-italiana",
});

const italianno = Italianno({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-italianno",
});

const tangerine = Tangerine({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-tangerine",
});

const DarumadropOne = Darumadrop_One({
  variable: "--font-Darumadrop-One-serif",
  subsets: ["latin"],
  weight: "400",
});

const jakartaSans = Plus_Jakarta_Sans({
  variable: "--font-jakarta-sans",
  subsets: ["latin"],
});
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-poppins",
});

const monaSans = Mona_Sans({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-mona-sans",
});

const figtree = Figtree({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-figtree",
});

const jetsBrainsMono = Geist_Mono({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-jetsBrains-mono",
});

const oswald = Oswald({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-oswald",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} ${monaSans.variable}
      ${montserrat.variable} ${jakartaSans.variable} ${DarumadropOne.variable} ${tangerine.variable} ${italiana.variable} 
      ${italianno.variable} ${figtree.variable} ${jetsBrainsMono.variable} ${oswald.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
